export const menuHighlights = [
  { name: "BBQ Chicken Pizza", image: "/assets/images/menu-highlights/bbq-chicken-pizza.jpg" },
  { name: "Chicken Lasagna", image: "/assets/images/menu-highlights/chicken-lasagna.jpg" },
  { name: "English Breakfast", image: "/assets/images/menu-highlights/english-breakfast.jpg" },
  { name: "Drums of Heaven", image: "/assets/images/menu-highlights/drums-of-heaven.jpg" },
  { name: "Chicken Stroganoff", image: "/assets/images/menu-highlights/chicken-stroganoff.jpg" },
  { name: "Cafe Special Grilled Chicken", image: "/assets/images/menu-highlights/cafe-special-grilled-chicken-with-massroom-sause.jpg" },
  { name: "Pina Colada", image: "/assets/images/menu-highlights/pina-colada-coconut-flavour.jpg" },
  { name: "Brownie with Vanilla Ice Cream", image: "/assets/images/menu-highlights/brownie-with-vanilla-ice-cream.jpg" },
  { name: "Blue Lagoon", image: "/assets/images/menu-highlights/blue-lagoon.jpg" },
  { name: "Fresh Lime Soda", image: "/assets/images/menu-highlights/fresh-lime-soda.jpg" },
  { name: "Grilled Chicken Mushroom", image: "/assets/images/menu-highlights/grilled-chicken-mushroom-sauce.jpg" },
  { name: "BBQ Pizza", image: "/assets/images/menu-highlights/bbq-pizza.jpg" },
  { name: "Cappuccino & Cookies", image: "/assets/images/menu-highlights/cappuccino-&-cookies.jpg" },
  { name: "Grilled Fish", image: "/assets/images/menu-highlights/grilled-fish-with-lemon-butter-sauce.jpg" },
  { name: "Cafe Latte", image: "/assets/images/menu-highlights/cafe-latte.jpg" },
  { name: "Fried Chicken Wontons", image: "/assets/images/menu-highlights/fried-chicken-wontons.jpg" },
  { name: "Barbecue Chicken Wings", image: "/assets/images/menu-highlights/barbecue-chicken-wings.jpg" },
  { name: "Crispy Chicken", image: "/assets/images/menu-highlights/crispy-chicken.jpg" },
  { name: "Chicken Sandwich", image: "/assets/images/menu-highlights/mustard-sauce-chicken-sandwich.jpg" },
  { name: "Meat Overload Pizza", image: "/assets/images/menu-highlights/meat-overload-pizza.jpg" },
];